# Generated by Django 5.2.6 on 2025-09-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/')),
                ('file_type', models.CharField(max_length=10)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('manual_validation', 'Manual Validation'), ('agent_validation', 'Agent Validation'), ('ai_analysis', 'AI Analysis'), ('autonomous_action', 'Autonomous Action')], max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('operation_details', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('compliant', models.BooleanField(default=False)),
                ('summary', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('contrast_errors', models.JSONField(default=list)),
                ('alerts', models.JSONField(default=list)),
                ('features', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('agent_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
